// <auto-generated />
using MagicCardsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicDatabase.Migrations
{
    [DbContext(typeof(MagicCardsContext))]
    [Migration("20250101215336_mssql_migration_562")]
    partial class mssql_migration_562
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicDatabase.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardRarityId")
                        .HasColumnType("int");

                    b.Property<int>("CardStatusId")
                        .HasColumnType("int");

                    b.HasKey("CardId");

                    b.HasIndex("CardRarityId");

                    b.HasIndex("CardStatusId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MagicDatabase.CardRarity", b =>
                {
                    b.Property<int>("CardRarityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardRarityId"));

                    b.Property<string>("RarityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardRarityId");

                    b.ToTable("CardRarities");
                });

            modelBuilder.Entity("MagicDatabase.CardStatus", b =>
                {
                    b.Property<int>("CardStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardStatusId");

                    b.ToTable("CardStatuses");
                });

            modelBuilder.Entity("MagicDatabase.Card", b =>
                {
                    b.HasOne("MagicDatabase.CardRarity", "CardRarity")
                        .WithMany()
                        .HasForeignKey("CardRarityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagicDatabase.CardStatus", "CardStatus")
                        .WithMany()
                        .HasForeignKey("CardStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardRarity");

                    b.Navigation("CardStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
