// <auto-generated />
using System;
using MagicCardsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicDatabase.Migrations
{
    [DbContext(typeof(MagicCardsContext))]
    [Migration("20250203123806_AddRevokedToRefreshToken")]
    partial class AddRevokedToRefreshToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicDatabase.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<int>("CardArtTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CardLanguageId")
                        .HasColumnType("int");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("CardRarityId")
                        .HasColumnType("int");

                    b.Property<int>("CardStatusId")
                        .HasColumnType("int");

                    b.Property<int>("CardSubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("CardId");

                    b.HasIndex("CardArtTypeId");

                    b.HasIndex("CardLanguageId");

                    b.HasIndex("CardRarityId");

                    b.HasIndex("CardStatusId");

                    b.HasIndex("CardSubCategoryId");

                    b.ToTable("Cards", (string)null);
                });

            modelBuilder.Entity("MagicDatabase.Models.CardArtType", b =>
                {
                    b.Property<int>("CardArtTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardArtTypeId"));

                    b.Property<string>("CardArtTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CardArtTypeId");

                    b.ToTable("CardArtTypes", (string)null);

                    b.HasData(
                        new
                        {
                            CardArtTypeId = 1,
                            CardArtTypeName = "Foil"
                        },
                        new
                        {
                            CardArtTypeId = 2,
                            CardArtTypeName = "Foil Etched"
                        },
                        new
                        {
                            CardArtTypeId = 3,
                            CardArtTypeName = "Reverse Foil"
                        },
                        new
                        {
                            CardArtTypeId = 4,
                            CardArtTypeName = "Full Art"
                        },
                        new
                        {
                            CardArtTypeId = 5,
                            CardArtTypeName = "Full Art Foil"
                        },
                        new
                        {
                            CardArtTypeId = 6,
                            CardArtTypeName = "Full Art Other Foilage"
                        },
                        new
                        {
                            CardArtTypeId = 7,
                            CardArtTypeName = "Double Art"
                        },
                        new
                        {
                            CardArtTypeId = 8,
                            CardArtTypeName = "Double Art Foil"
                        },
                        new
                        {
                            CardArtTypeId = 9,
                            CardArtTypeName = "Borderless"
                        },
                        new
                        {
                            CardArtTypeId = 10,
                            CardArtTypeName = "Borderless Foil"
                        },
                        new
                        {
                            CardArtTypeId = 11,
                            CardArtTypeName = "Alternative Art"
                        },
                        new
                        {
                            CardArtTypeId = 12,
                            CardArtTypeName = "Alternative Art Foil"
                        },
                        new
                        {
                            CardArtTypeId = 13,
                            CardArtTypeName = "Promo"
                        },
                        new
                        {
                            CardArtTypeId = 14,
                            CardArtTypeName = "Promo Foil"
                        },
                        new
                        {
                            CardArtTypeId = 15,
                            CardArtTypeName = "Missprint"
                        },
                        new
                        {
                            CardArtTypeId = 16,
                            CardArtTypeName = "None"
                        });
                });

            modelBuilder.Entity("MagicDatabase.Models.CardCategory", b =>
                {
                    b.Property<int>("CardCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardCategoryId"));

                    b.Property<string>("CardCategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CardCategoryId");

                    b.ToTable("CardCategories", (string)null);

                    b.HasData(
                        new
                        {
                            CardCategoryId = 1,
                            CardCategoryName = "Creatura"
                        },
                        new
                        {
                            CardCategoryId = 2,
                            CardCategoryName = "Incantesimo"
                        },
                        new
                        {
                            CardCategoryId = 3,
                            CardCategoryName = "Artefatto"
                        },
                        new
                        {
                            CardCategoryId = 4,
                            CardCategoryName = "Terra"
                        },
                        new
                        {
                            CardCategoryId = 5,
                            CardCategoryName = "Planeswalker"
                        },
                        new
                        {
                            CardCategoryId = 6,
                            CardCategoryName = "Istantaneo"
                        },
                        new
                        {
                            CardCategoryId = 7,
                            CardCategoryName = "Stregoneria"
                        });
                });

            modelBuilder.Entity("MagicDatabase.Models.CardLanguage", b =>
                {
                    b.Property<int>("CardLanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardLanguageId"));

                    b.Property<string>("CardLanguageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CardLanguageId");

                    b.ToTable("CardLanguages", (string)null);

                    b.HasData(
                        new
                        {
                            CardLanguageId = 1,
                            CardLanguageName = "Italian"
                        },
                        new
                        {
                            CardLanguageId = 2,
                            CardLanguageName = "English"
                        },
                        new
                        {
                            CardLanguageId = 3,
                            CardLanguageName = "Japanese"
                        },
                        new
                        {
                            CardLanguageId = 4,
                            CardLanguageName = "French"
                        },
                        new
                        {
                            CardLanguageId = 5,
                            CardLanguageName = "German"
                        },
                        new
                        {
                            CardLanguageId = 6,
                            CardLanguageName = "Russian"
                        },
                        new
                        {
                            CardLanguageId = 7,
                            CardLanguageName = "Spanish"
                        },
                        new
                        {
                            CardLanguageId = 8,
                            CardLanguageName = "Portuguese"
                        },
                        new
                        {
                            CardLanguageId = 9,
                            CardLanguageName = "Chinese"
                        },
                        new
                        {
                            CardLanguageId = 10,
                            CardLanguageName = "Korean"
                        });
                });

            modelBuilder.Entity("MagicDatabase.Models.CardRarity", b =>
                {
                    b.Property<int>("CardRarityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardRarityId"));

                    b.Property<string>("CardRarityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CardRarityId");

                    b.ToTable("CardRarities", (string)null);

                    b.HasData(
                        new
                        {
                            CardRarityId = 1,
                            CardRarityName = "Common"
                        },
                        new
                        {
                            CardRarityId = 2,
                            CardRarityName = "Uncommon"
                        },
                        new
                        {
                            CardRarityId = 3,
                            CardRarityName = "Rare"
                        },
                        new
                        {
                            CardRarityId = 4,
                            CardRarityName = "Mythic Rare"
                        });
                });

            modelBuilder.Entity("MagicDatabase.Models.CardStatus", b =>
                {
                    b.Property<int>("CardStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardStatusId"));

                    b.Property<string>("CardStatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CardStatusId");

                    b.ToTable("CardStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            CardStatusId = 1,
                            CardStatusName = "Trashed"
                        },
                        new
                        {
                            CardStatusId = 2,
                            CardStatusName = "Damaged"
                        },
                        new
                        {
                            CardStatusId = 3,
                            CardStatusName = "Poor"
                        },
                        new
                        {
                            CardStatusId = 4,
                            CardStatusName = "Heavily Played"
                        },
                        new
                        {
                            CardStatusId = 5,
                            CardStatusName = "Lightly Played"
                        },
                        new
                        {
                            CardStatusId = 6,
                            CardStatusName = "Good"
                        },
                        new
                        {
                            CardStatusId = 7,
                            CardStatusName = "Excellent"
                        },
                        new
                        {
                            CardStatusId = 8,
                            CardStatusName = "Near Mint"
                        },
                        new
                        {
                            CardStatusId = 9,
                            CardStatusName = "Mint"
                        },
                        new
                        {
                            CardStatusId = 10,
                            CardStatusName = "Sealed"
                        });
                });

            modelBuilder.Entity("MagicDatabase.Models.CardSubCategory", b =>
                {
                    b.Property<int>("CardSubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardSubCategoryId"));

                    b.Property<int>("CardCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("CardSubCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardSubCategoryId");

                    b.HasIndex("CardCategoryID");

                    b.ToTable("CardSubCategories", (string)null);

                    b.HasData(
                        new
                        {
                            CardSubCategoryId = 1,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Elfo"
                        },
                        new
                        {
                            CardSubCategoryId = 2,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Zombie"
                        },
                        new
                        {
                            CardSubCategoryId = 3,
                            CardCategoryID = 2,
                            CardSubCategoryName = "Aura"
                        },
                        new
                        {
                            CardSubCategoryId = 4,
                            CardCategoryID = 3,
                            CardSubCategoryName = "Equipaggiamento"
                        },
                        new
                        {
                            CardSubCategoryId = 5,
                            CardCategoryID = 3,
                            CardSubCategoryName = "Cibo"
                        },
                        new
                        {
                            CardSubCategoryId = 6,
                            CardCategoryID = 3,
                            CardSubCategoryName = "Indizio"
                        },
                        new
                        {
                            CardSubCategoryId = 7,
                            CardCategoryID = 3,
                            CardSubCategoryName = "Tesoro"
                        },
                        new
                        {
                            CardSubCategoryId = 8,
                            CardCategoryID = 3,
                            CardSubCategoryName = "Sangue"
                        },
                        new
                        {
                            CardSubCategoryId = 9,
                            CardCategoryID = 3,
                            CardSubCategoryName = "Veicolo"
                        },
                        new
                        {
                            CardSubCategoryId = 10,
                            CardCategoryID = 3,
                            CardSubCategoryName = "Oro"
                        },
                        new
                        {
                            CardSubCategoryId = 11,
                            CardCategoryID = 2,
                            CardSubCategoryName = "Saga"
                        },
                        new
                        {
                            CardSubCategoryId = 12,
                            CardCategoryID = 2,
                            CardSubCategoryName = "Santuario"
                        },
                        new
                        {
                            CardSubCategoryId = 13,
                            CardCategoryID = 4,
                            CardSubCategoryName = "Cancello"
                        },
                        new
                        {
                            CardSubCategoryId = 14,
                            CardCategoryID = 4,
                            CardSubCategoryName = "Deserto"
                        },
                        new
                        {
                            CardSubCategoryId = 15,
                            CardCategoryID = 4,
                            CardSubCategoryName = "Pianura"
                        },
                        new
                        {
                            CardSubCategoryId = 16,
                            CardCategoryID = 4,
                            CardSubCategoryName = "Isola"
                        },
                        new
                        {
                            CardSubCategoryId = 17,
                            CardCategoryID = 4,
                            CardSubCategoryName = "Foresta"
                        },
                        new
                        {
                            CardSubCategoryId = 18,
                            CardCategoryID = 4,
                            CardSubCategoryName = "Palude"
                        },
                        new
                        {
                            CardSubCategoryId = 19,
                            CardCategoryID = 4,
                            CardSubCategoryName = "Montagna"
                        },
                        new
                        {
                            CardSubCategoryId = 20,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Consigliere"
                        },
                        new
                        {
                            CardSubCategoryId = 21,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Alleato"
                        },
                        new
                        {
                            CardSubCategoryId = 22,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Arciere"
                        },
                        new
                        {
                            CardSubCategoryId = 23,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Scimpanzè"
                        },
                        new
                        {
                            CardSubCategoryId = 24,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Antilope"
                        },
                        new
                        {
                            CardSubCategoryId = 25,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Angelo"
                        },
                        new
                        {
                            CardSubCategoryId = 26,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Arconte"
                        },
                        new
                        {
                            CardSubCategoryId = 27,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Esercito"
                        },
                        new
                        {
                            CardSubCategoryId = 28,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Artefice"
                        },
                        new
                        {
                            CardSubCategoryId = 29,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Assassino"
                        },
                        new
                        {
                            CardSubCategoryId = 30,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Addetto al Montaggio"
                        },
                        new
                        {
                            CardSubCategoryId = 31,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Atog"
                        },
                        new
                        {
                            CardSubCategoryId = 32,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Uri"
                        },
                        new
                        {
                            CardSubCategoryId = 33,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Avatar"
                        },
                        new
                        {
                            CardSubCategoryId = 34,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Azra"
                        },
                        new
                        {
                            CardSubCategoryId = 35,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Tasso"
                        },
                        new
                        {
                            CardSubCategoryId = 36,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Barbaro"
                        },
                        new
                        {
                            CardSubCategoryId = 37,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Bardo"
                        },
                        new
                        {
                            CardSubCategoryId = 38,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Basilisco"
                        },
                        new
                        {
                            CardSubCategoryId = 39,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Pipistrello"
                        },
                        new
                        {
                            CardSubCategoryId = 40,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Orso"
                        },
                        new
                        {
                            CardSubCategoryId = 41,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Bestia"
                        },
                        new
                        {
                            CardSubCategoryId = 42,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Bibolo"
                        },
                        new
                        {
                            CardSubCategoryId = 43,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Berserker"
                        },
                        new
                        {
                            CardSubCategoryId = 44,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Uccello"
                        },
                        new
                        {
                            CardSubCategoryId = 45,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Lampidottero"
                        },
                        new
                        {
                            CardSubCategoryId = 46,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Cinghiale"
                        },
                        new
                        {
                            CardSubCategoryId = 47,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Portatore"
                        },
                        new
                        {
                            CardSubCategoryId = 48,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Burlarbusto"
                        },
                        new
                        {
                            CardSubCategoryId = 49,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Camarid"
                        },
                        new
                        {
                            CardSubCategoryId = 50,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Cammello"
                        },
                        new
                        {
                            CardSubCategoryId = 51,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Caribù"
                        },
                        new
                        {
                            CardSubCategoryId = 52,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Felino"
                        },
                        new
                        {
                            CardSubCategoryId = 53,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Centauro"
                        },
                        new
                        {
                            CardSubCategoryId = 54,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Cefalide"
                        },
                        new
                        {
                            CardSubCategoryId = 55,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Chimera"
                        },
                        new
                        {
                            CardSubCategoryId = 56,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Cittadino"
                        },
                        new
                        {
                            CardSubCategoryId = 57,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Chierico"
                        },
                        new
                        {
                            CardSubCategoryId = 58,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Coccatrice"
                        },
                        new
                        {
                            CardSubCategoryId = 59,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Costrutto"
                        },
                        new
                        {
                            CardSubCategoryId = 60,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Vigliacco"
                        },
                        new
                        {
                            CardSubCategoryId = 61,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Granchio"
                        },
                        new
                        {
                            CardSubCategoryId = 62,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Coccodrillo"
                        },
                        new
                        {
                            CardSubCategoryId = 63,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Ciclope"
                        },
                        new
                        {
                            CardSubCategoryId = 64,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Dauthi"
                        },
                        new
                        {
                            CardSubCategoryId = 65,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Semidio"
                        },
                        new
                        {
                            CardSubCategoryId = 66,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Demone"
                        },
                        new
                        {
                            CardSubCategoryId = 67,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Disertore"
                        },
                        new
                        {
                            CardSubCategoryId = 68,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Diavolo"
                        },
                        new
                        {
                            CardSubCategoryId = 69,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Dinosauro"
                        },
                        new
                        {
                            CardSubCategoryId = 70,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Genio"
                        },
                        new
                        {
                            CardSubCategoryId = 71,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Canide"
                        },
                        new
                        {
                            CardSubCategoryId = 72,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Drago"
                        },
                        new
                        {
                            CardSubCategoryId = 73,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Draghetto"
                        },
                        new
                        {
                            CardSubCategoryId = 74,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Sterminatore"
                        },
                        new
                        {
                            CardSubCategoryId = 75,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Drone"
                        },
                        new
                        {
                            CardSubCategoryId = 76,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Druido"
                        },
                        new
                        {
                            CardSubCategoryId = 77,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Driade"
                        },
                        new
                        {
                            CardSubCategoryId = 78,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Nano"
                        },
                        new
                        {
                            CardSubCategoryId = 79,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Efreet"
                        },
                        new
                        {
                            CardSubCategoryId = 80,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Uovo"
                        },
                        new
                        {
                            CardSubCategoryId = 81,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Antico"
                        },
                        new
                        {
                            CardSubCategoryId = 82,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Eldrazi"
                        },
                        new
                        {
                            CardSubCategoryId = 83,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Elementale"
                        },
                        new
                        {
                            CardSubCategoryId = 84,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Elefante"
                        },
                        new
                        {
                            CardSubCategoryId = 85,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Alce"
                        },
                        new
                        {
                            CardSubCategoryId = 86,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Occhio"
                        },
                        new
                        {
                            CardSubCategoryId = 87,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Spiritello"
                        },
                        new
                        {
                            CardSubCategoryId = 88,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Furetto"
                        },
                        new
                        {
                            CardSubCategoryId = 89,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Pesce"
                        },
                        new
                        {
                            CardSubCategoryId = 90,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Portabandiera"
                        },
                        new
                        {
                            CardSubCategoryId = 91,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Volpe"
                        },
                        new
                        {
                            CardSubCategoryId = 92,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Frattale"
                        },
                        new
                        {
                            CardSubCategoryId = 93,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Rana"
                        },
                        new
                        {
                            CardSubCategoryId = 94,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Fungus"
                        },
                        new
                        {
                            CardSubCategoryId = 95,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Gargoyle"
                        },
                        new
                        {
                            CardSubCategoryId = 96,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Microbo"
                        },
                        new
                        {
                            CardSubCategoryId = 97,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Gigante"
                        },
                        new
                        {
                            CardSubCategoryId = 98,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Gnomo"
                        },
                        new
                        {
                            CardSubCategoryId = 99,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Capra"
                        },
                        new
                        {
                            CardSubCategoryId = 100,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Dio"
                        },
                        new
                        {
                            CardSubCategoryId = 101,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Goblin"
                        },
                        new
                        {
                            CardSubCategoryId = 102,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Golem"
                        },
                        new
                        {
                            CardSubCategoryId = 103,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Gorgone"
                        },
                        new
                        {
                            CardSubCategoryId = 104,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Figlio della Tomba"
                        },
                        new
                        {
                            CardSubCategoryId = 105,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Gremlin"
                        },
                        new
                        {
                            CardSubCategoryId = 106,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Grifone"
                        },
                        new
                        {
                            CardSubCategoryId = 107,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Strega"
                        },
                        new
                        {
                            CardSubCategoryId = 108,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Criceto"
                        },
                        new
                        {
                            CardSubCategoryId = 109,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Arpia"
                        },
                        new
                        {
                            CardSubCategoryId = 110,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Infernale"
                        },
                        new
                        {
                            CardSubCategoryId = 111,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Ippopotamo"
                        },
                        new
                        {
                            CardSubCategoryId = 112,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Ippogrifo"
                        },
                        new
                        {
                            CardSubCategoryId = 113,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Homarid"
                        },
                        new
                        {
                            CardSubCategoryId = 114,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Omuncolo"
                        },
                        new
                        {
                            CardSubCategoryId = 115,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Orrore"
                        },
                        new
                        {
                            CardSubCategoryId = 116,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Cavallo"
                        },
                        new
                        {
                            CardSubCategoryId = 117,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Umano"
                        },
                        new
                        {
                            CardSubCategoryId = 118,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Idra"
                        },
                        new
                        {
                            CardSubCategoryId = 119,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Iena"
                        },
                        new
                        {
                            CardSubCategoryId = 120,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Illusione"
                        },
                        new
                        {
                            CardSubCategoryId = 121,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Imp"
                        },
                        new
                        {
                            CardSubCategoryId = 122,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Incarnazione"
                        },
                        new
                        {
                            CardSubCategoryId = 123,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Scarabocchio"
                        },
                        new
                        {
                            CardSubCategoryId = 124,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Insetto"
                        },
                        new
                        {
                            CardSubCategoryId = 125,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Sciacallo"
                        },
                        new
                        {
                            CardSubCategoryId = 126,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Medusa"
                        },
                        new
                        {
                            CardSubCategoryId = 127,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Juggernaut"
                        },
                        new
                        {
                            CardSubCategoryId = 128,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Kavu"
                        },
                        new
                        {
                            CardSubCategoryId = 129,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Kirin"
                        },
                        new
                        {
                            CardSubCategoryId = 130,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Kithkin"
                        },
                        new
                        {
                            CardSubCategoryId = 131,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Cavaliere"
                        },
                        new
                        {
                            CardSubCategoryId = 132,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Coboldo"
                        },
                        new
                        {
                            CardSubCategoryId = 133,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Kor"
                        },
                        new
                        {
                            CardSubCategoryId = 134,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Kraken"
                        },
                        new
                        {
                            CardSubCategoryId = 135,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Lamia"
                        },
                        new
                        {
                            CardSubCategoryId = 136,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Lammasu"
                        },
                        new
                        {
                            CardSubCategoryId = 137,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Sanguisuga"
                        },
                        new
                        {
                            CardSubCategoryId = 138,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Leviatano"
                        },
                        new
                        {
                            CardSubCategoryId = 139,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Lhurgoyf"
                        },
                        new
                        {
                            CardSubCategoryId = 140,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Licide"
                        },
                        new
                        {
                            CardSubCategoryId = 141,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Lucertola"
                        },
                        new
                        {
                            CardSubCategoryId = 142,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Manticora"
                        },
                        new
                        {
                            CardSubCategoryId = 143,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Masticora"
                        },
                        new
                        {
                            CardSubCategoryId = 144,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Mercenario"
                        },
                        new
                        {
                            CardSubCategoryId = 145,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Tritone"
                        },
                        new
                        {
                            CardSubCategoryId = 146,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Metathran"
                        },
                        new
                        {
                            CardSubCategoryId = 147,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Servitore"
                        },
                        new
                        {
                            CardSubCategoryId = 148,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Minotauro"
                        },
                        new
                        {
                            CardSubCategoryId = 149,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Talpa"
                        },
                        new
                        {
                            CardSubCategoryId = 150,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Commerciante"
                        },
                        new
                        {
                            CardSubCategoryId = 151,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Mangusta"
                        },
                        new
                        {
                            CardSubCategoryId = 152,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Monaco"
                        },
                        new
                        {
                            CardSubCategoryId = 153,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Scimmia"
                        },
                        new
                        {
                            CardSubCategoryId = 154,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Lunantropo"
                        },
                        new
                        {
                            CardSubCategoryId = 155,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Mutante"
                        },
                        new
                        {
                            CardSubCategoryId = 156,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Myr"
                        },
                        new
                        {
                            CardSubCategoryId = 157,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Mistico"
                        },
                        new
                        {
                            CardSubCategoryId = 158,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Naga"
                        },
                        new
                        {
                            CardSubCategoryId = 159,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Nautilo"
                        },
                        new
                        {
                            CardSubCategoryId = 160,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Nephilim"
                        },
                        new
                        {
                            CardSubCategoryId = 161,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Incubo"
                        },
                        new
                        {
                            CardSubCategoryId = 162,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Topo"
                        },
                        new
                        {
                            CardSubCategoryId = 163,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Cacciatore Notturno"
                        },
                        new
                        {
                            CardSubCategoryId = 164,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Ninja"
                        },
                        new
                        {
                            CardSubCategoryId = 165,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Nobile"
                        },
                        new
                        {
                            CardSubCategoryId = 166,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Noggle"
                        },
                        new
                        {
                            CardSubCategoryId = 167,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Nomade"
                        },
                        new
                        {
                            CardSubCategoryId = 168,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Ninfa"
                        },
                        new
                        {
                            CardSubCategoryId = 169,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Piovra"
                        },
                        new
                        {
                            CardSubCategoryId = 170,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Ogre"
                        },
                        new
                        {
                            CardSubCategoryId = 171,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Melma"
                        },
                        new
                        {
                            CardSubCategoryId = 172,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Globo"
                        },
                        new
                        {
                            CardSubCategoryId = 173,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Orco"
                        },
                        new
                        {
                            CardSubCategoryId = 174,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Lontra"
                        },
                        new
                        {
                            CardSubCategoryId = 175,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Servomeccanismo"
                        },
                        new
                        {
                            CardSubCategoryId = 176,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Scheggia"
                        },
                        new
                        {
                            CardSubCategoryId = 177,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Tentacolo"
                        },
                        new
                        {
                            CardSubCategoryId = 178,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Troll"
                        },
                        new
                        {
                            CardSubCategoryId = 179,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Tartaruga"
                        },
                        new
                        {
                            CardSubCategoryId = 180,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Unicorno"
                        },
                        new
                        {
                            CardSubCategoryId = 181,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Vampiro"
                        },
                        new
                        {
                            CardSubCategoryId = 182,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Vedalken"
                        },
                        new
                        {
                            CardSubCategoryId = 183,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Viashino"
                        },
                        new
                        {
                            CardSubCategoryId = 184,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Muro"
                        },
                        new
                        {
                            CardSubCategoryId = 185,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Guerriero"
                        },
                        new
                        {
                            CardSubCategoryId = 186,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Mannaro"
                        },
                        new
                        {
                            CardSubCategoryId = 187,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Balena"
                        },
                        new
                        {
                            CardSubCategoryId = 188,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Mago"
                        },
                        new
                        {
                            CardSubCategoryId = 189,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Lupo"
                        },
                        new
                        {
                            CardSubCategoryId = 190,
                            CardCategoryID = 1,
                            CardSubCategoryName = "Zubera"
                        });
                });

            modelBuilder.Entity("MagicDatabase.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("MagicDatabase.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAEKjoMC6eGqroONRG0bL9QtCltlkYW7kuJAcRe+8guLskScy2nHJtQ0xLcNKC7b80VQ==",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            PasswordHash = "AQAAAAIAAYagAAAAEDGm9i0zw5UsXrJKIaIBW2XCJgm6zFeMeMpbLjEYyPpKtDnVmcbvqXMoTyQqSLvWKA==",
                            Role = "User",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("MagicDatabase.Models.Card", b =>
                {
                    b.HasOne("MagicDatabase.Models.CardArtType", "CardArtType")
                        .WithMany()
                        .HasForeignKey("CardArtTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagicDatabase.Models.CardLanguage", "CardLanguage")
                        .WithMany()
                        .HasForeignKey("CardLanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagicDatabase.Models.CardRarity", "CardRarity")
                        .WithMany()
                        .HasForeignKey("CardRarityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagicDatabase.Models.CardStatus", "CardStatus")
                        .WithMany()
                        .HasForeignKey("CardStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagicDatabase.Models.CardSubCategory", "CardSubCategory")
                        .WithMany()
                        .HasForeignKey("CardSubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardArtType");

                    b.Navigation("CardLanguage");

                    b.Navigation("CardRarity");

                    b.Navigation("CardStatus");

                    b.Navigation("CardSubCategory");
                });

            modelBuilder.Entity("MagicDatabase.Models.CardSubCategory", b =>
                {
                    b.HasOne("MagicDatabase.Models.CardCategory", "CardCategory")
                        .WithMany("CardSubCategories")
                        .HasForeignKey("CardCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardCategory");
                });

            modelBuilder.Entity("MagicDatabase.Models.CardCategory", b =>
                {
                    b.Navigation("CardSubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
